[http.middlewares]
  [http.middlewares.global-rate-limit.ratelimit]
    average = 60
    burst = 20
  [http.middlewares.login-rate-limit.ratelimit]
    average = 10
    burst = 5
  [http.middlewares.api-rate-limit.ratelimit]
    average = 120
    burst = 40
  [http.middlewares.search-rate-limit.ratelimit]
    average = 100
    burst = 20
[http.routers]
  [http.routers.my-router.middlewares]
    - global-rate-limit
  [http.routers.my-router.middlewares]
    - login-rate-limit
  [http.routers.my-router.middlewares]
    - api-rate-limit
  [http.routers.my-router.middlewares]
    - search-rate-limit
