limit_req_zone $binary_remote_addr zone=default:10m rate=60r/1min;
limit_req_zone $binary_remote_addr zone=login:10m rate=10r/1min;
limit_req_zone $binary_remote_addr zone=api:10m rate=120r/1min;
limit_req_zone $binary_remote_addr zone=search:10m rate=100r/1min;
server {
  location / {
    limit_req zone=default burst=20 nodelay;
    ... # Your other configurations here
  }
  location /login {
    limit_req zone=login burst=5 nodelay;
    ... # Your other configurations here
  }
  location /api {
    limit_req zone=api burst=40 nodelay;
    ... # Your other configurations here
  }
  location /search/(.*) {
    limit_req zone=search burst=20 nodelay;
    ... # Your other configurations here
  }
}
