# default: 60 requests per 1m
limit_req_zone $binary_remote_addr zone=default:10m rate=1r/s;
# /login: 10 requests per 1m
limit_req_zone $binary_remote_addr zone=login:10m rate=10r/m;
# /api: 120 requests per 1m
limit_req_zone $binary_remote_addr zone=api:10m rate=2r/s;
# /search/(.*): 100 requests per 1m
limit_req_zone $binary_remote_addr zone=search:10m rate=100r/m;
server {
  location / {
    limit_req zone=default burst=20 nodelay;
    # Add the directives that serve this location here.
  }
  location /login {
    limit_req zone=login burst=5 nodelay;
    # Add the directives that serve this location here.
  }
  location /api {
    limit_req zone=api burst=40 nodelay;
    # Add the directives that serve this location here.
  }
  location /search/(.*) {
    limit_req zone=search burst=20 nodelay;
    # Add the directives that serve this location here.
  }
}
