acl global_rate_limit src_conn_rate_ge 60
http-request deny if global_rate_limit
acl is_login path_beg /login
acl login_rate_limit src_conn_rate_ge 10
http-request deny if is_login login_rate_limit
acl is_api path_beg /api
acl api_rate_limit src_conn_rate_ge 120
http-request deny if is_api api_rate_limit
acl is_search path_beg /search/(.*)
acl search_rate_limit src_conn_rate_ge 100
http-request deny if is_search search_rate_limit
